### PR TITLE
Initial support Lightning Returns

### PR DESCRIPTION
**Pull request by RustedGames**
Initial support Lightning Returns

### CODE REVIEW

**Comment by marcussacana** [comment]
OH MY FUCKING GOD

**Comment by Albeoris** [comment]
Thank you, I'll do it soon.

**Comment by Albeoris** [comment]
The rull request contains changes which do not relate to the support of the FFXIII-3 and cannot be merged directly.

Lang: I will add both files.
Messages: I will add it to Lang.
Patcher: It's not a part of the Pulse. I will try to make it convenient.

**Comment by weirdalsuperfan** [comment]
Any update on this?

**Comment by marcussacana** [comment]
2 Years, just forgget, dropped.

**Comment by Albeoris** [comment]
Yeah, sorry.
Actual version with support of LR available here: https://github.com/rhadamants/Pulse

**Pull request closed without merging**
